### PR TITLE
fix and refactor cache_info_with_warnings

### LINKED ISSUE #1105: "-P --stats" not displaying orphans, and out-of-date packages on 2.0.1
### Affected Version
paru v2.0.1 - libalpm v13.0.2

### Description
reading the man page of paru "--stats" reads it will display installed packages and system health along with displaying orphan, out-of-date, and not-in-the-aur packages but when running with that flag only the not-in-the-aur packages are shown even though regular paru can detect out-of-date and orphan packages

### Output
paru
```
:: marked out of date: detect-it-easy  fbx2gltf-bin  inky  lib32-libass  lib32-libcue  libadwaita-git  libcyaml
    libglibutil  localsend-bin  lsp-dsp-lib  nss-hg  nvidia-container-toolkit  perl-http-server-simple-psgi  
    perl-router-simple  perl-test-sharedfork  pyinstaller-hooks-contrib  python-mypy-protobuf  python-node-semver
    python-pluginbase  python-stringcase  python-svg.path  python2-decorator  ttf-monapo  twinejs-standalone
:: orphans: cpptoml  java11-openjfx  lib32-libcue  lib32-libdvdcss  libcyaml  libnest2d  perl-fcgi-procmanager  
    perl-lwp-protocol-http10  perl-plack  perl-router-simple  python-baron  python-colormath  sdl2_sound-git  
    vpuppr-bin
```
paru -Ps

```
paru v2.0.1 - libalpm v13.0.2
===========================================
Total installed packages: 4210
Aur packages: 472
Repo packages: 3728
Explicitly installed packages: 1132
Total Size occupied by packages: 76.24 GiB
===========================================
Ten biggest packages:
kicad-library-3d: 5.43 GiB
cuda: 4.35 GiB
cuda-tools: 2.44 GiB
intellij-idea-ce: 2.38 GiB
flutter: 1.52 GiB
mse-mtg-m15: 1.46 GiB
texlive-fontsextra: 1.40 GiB
jdk-openjdk: 1.11 GiB
lazarus: 1.05 GiB
ghidra: 969.44 MiB
===========================================
:: packages not in the AUR: dialog-lang  japanese-text-analysis-tool  lib32-ffmpeg-debug  
    mse-fonts  ndc-bin  pmdmini-git  qtcsv-qt5-git  wine-tkg-fsync-git  x16-user-guide-git
```
<details>
<summary>paru.conf</summary>
<p>
<pre>

#
# $PARU_CONF
# /etc/paru.conf
# ~/.config/paru/paru.conf
#
# See the paru.conf(5) manpage for options

#
# GENERAL OPTIONS
#
[options]
#PgpFetch
#Devel
#Provides
#DevelSuffixes = -git -cvs -svn -bzr -darcs -always -hg -fossil
#AurOnly
#BottomUp
#RemoveMake
#SudoLoop
#UseAsk
#SaveChanges
#CombinedUpgrade
#CleanAfter
UpgradeMenu
#NewsOnUpgrade
BatchInstall
#LocalRepo
#Chroot
#Sign
#SignDb
#KeepRepoCache

#
# Binary OPTIONS
#
#[bin]
#FileManager = vifm
#MFlags = --skippgpcheck
#Sudo = doas

[Silver]
Url = https://github.com/silverhikari/my-archlinux-packages.git
Depth = 2
</pre>
</p>
</details>

<details>
<summary>pacman.conf</summary>
<p>
<pre>
#
# /etc/pacman.conf
#
# See the pacman.conf(5) manpage for option and repository directives

#
# GENERAL OPTIONS
#
[options]
# The following paths are commented out with their default values listed.
# If you wish to use different paths, uncomment and update the paths.
#RootDir     = /
#DBPath      = /var/lib/pacman/
CacheDir = /var/cache/pacman/pkg/
#LogFile     = /var/log/pacman.log
#GPGDir      = /etc/pacman.d/gnupg/
#HookDir     = /etc/pacman.d/hooks/
HoldPkg      = pacman glibc manjaro-system
# If upgrades are available for these packages they will be asked for first
SyncFirst    = manjaro-system archlinux-keyring manjaro-keyring
#XferCommand = /usr/bin/curl -L -C - -f -o %o %u
#XferCommand = /usr/bin/wget --passive-ftp -c -O %o %u
#CleanMethod = KeepInstalled
Architecture = auto

# Pacman won't upgrade packages listed in IgnorePkg and members of IgnoreGroup
#IgnorePkg   =
#IgnoreGroup =

#NoUpgrade   =
#NoExtract   =

# Misc options
#UseSyslog
Color
#NoProgressBar
CheckSpace
#VerbosePkgLists
ParallelDownloads = 4
ILoveCandy

# By default, pacman accepts packages signed by keys that its local keyring
# trusts (see pacman-key and its man page), as well as unsigned packages.
SigLevel    = Required DatabaseOptional
LocalFileSigLevel = Optional
#RemoteFileSigLevel = Required

# NOTE: You must run `pacman-key --init` before first using pacman; the local
# keyring can then be populated with the keys of all official Manjaro Linux
# packagers with `pacman-key --populate archlinux manjaro`.

#
# REPOSITORIES
#   - can be defined here or included from another file
#   - pacman will search repositories in the order defined here
#   - local/custom mirrors can be added here or in separate files
#   - repositories listed first will take precedence when packages
#     have identical names, regardless of version number
#   - URLs will have $repo replaced by the name of the current repo
#   - URLs will have $arch replaced by the name of the architecture
#
# Repository entries are of the format:
#       [repo-name]
#       Server = ServerName
#       Include = IncludePath
#
# The header [repo-name] is crucial - it must be present and
# uncommented to enable the repo.
#

[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist

# If you want to run 32 bit applications on your x86_64 system,
# enable the multilib repositories as required here.

[multilib]
Include = /etc/pacman.d/mirrorlist

[dkp-libs]
Server = https://pkg.devkitpro.org/packages

[dkp-linux]
Server = https://pkg.devkitpro.org/packages/linux/$arch/

# An example of a custom package repository.  See the pacman manpage for
# tips on creating your own repositories.
#[custom]
#SigLevel = Optional TrustAll
#Server = file:///home/custompkgs

</pre>
</p>
</details>

### PR DESCRIPTION
**Pull request by romanstingler**
fixes #1105

added the missing  ! in `!no_warn` block for ood and orphaned. 
refactored the whole method, removed unwraps and improved readability.

### CODE REVIEW

File: src/download.rs [hunk 1]
```diff
@@ -138,39 +138,44 @@ pub async fn cache_info_with_warnings<'a, S: AsRef<str> + Send + Sync>(
...
+        if should_warn(pkg_name) && !cache.contains(pkg_name) {
+            missing.push(pkg_name);
         }
     }
 
     for pkg in &aur_pkgs {
-        if no_warn.is_match(&pkg.name) && !ignore.iter().any(|p| p.as_str() == pkg.name) {
+        if should_warn(&pkg.name) {
             if pkg.out_of_date.is_some() {
-                ood.push(cache.get(pkg.name.as_str()).unwrap().name.as_str());
```
Comment (Morganamilo) [inline src/download.rs:157]: aur_pkgs comes from a call to raur.cache_info(). If a name is in the returned list it must also be in cache, so the unwraps are fine. Rest looks good to me,

Comment (romanstingler) [reply src/download.rs:157]: thanks, missed that
