### PR TITLE
fix: handle PkgNotFound gracefully in query operations

### LINKED ISSUE #1340: paru -Qui crashes
### Affected Version
**paru -V**
```
> paru -V
paru v2.0.4 - libalpm v15.0.0
```
### Description
might be connected with the fact that paru tries to install long ago removed by me git versions of hyprwayland-scanner-git and hyprutils-git

### Output
```
> RUST_BACKTRACE=full paru -Qui
thread 'main' panicked at /usr/src/debug/paru/paru-2.0.4/src/query.rs:70:48:
called `Result::unwrap()` on an `Err` value: PkgNotFound
stack backtrace:
   0:     0x57f6c979ddba - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hd736fd5964392270
   1:     0x57f6c946bf7b - core::fmt::write::hc6043626647b98ea
   2:     0x57f6c97674b2 - std::io::Write::write_fmt::h0d24b3e0473045db
   3:     0x57f6c97a0d39 - std::sys_common::backtrace::print::h45eb8174d25a1e76
   4:     0x57f6c97a0526 - std::panicking::default_hook::{{closure}}::haf3f0170eb4f3b53
   5:     0x57f6c97a1979 - std::panicking::rust_panic_with_hook::h6b49d59f86ee588c
   6:     0x57f6c97a10a2 - std::panicking::begin_panic_handler::{{closure}}::hd4c2f7ed79b82b70
   7:     0x57f6c97a0ff9 - std::sys_common::backtrace::__rust_end_short_backtrace::h2946d6d32d7ea1ad
   8:     0x57f6c97a0fe6 - rust_begin_unwind
   9:     0x57f6c9308d82 - core::panicking::panic_fmt::ha02418e5cd774672
  10:     0x57f6c9309245 - core::result::unwrap_failed::h55f86ada3ace5ed2
  11:     0x57f6c93fc140 - alloc::vec::Vec<T,A>::retain::{{closure}}::h1664e71b439673bc
  12:     0x57f6c93fb9e1 - alloc::vec::Vec<T,A>::retain::hdc1feed584641069
  13:     0x57f6c9391df2 - paru::handle_query::{{closure}}::h8c370074a4d0bc35
  14:     0x57f6c93a5e87 - paru::run2::{{closure}}::h3b9595393049eb5c
  15:     0x57f6c941780c - paru::main::{{closure}}::h96b34c6ec8c50dba
  16:     0x57f6c941475b - paru::main::hb2ffc05fdae96d23
  17:     0x57f6c9357696 - std::sys_common::backtrace::__rust_begin_short_backtrace::h51cd1c00e0994245
  18:     0x57f6c94186cb - main
  19:     0x7f6eea50f488 - <unknown>
  20:     0x7f6eea50f54c - __libc_start_main
  21:     0x57f6c9327a55 - _start
  22:                0x0 - <unknown>
```
**paru.conf and pacman.conf are usually always relevant**
did not create a paru.conf
## pacman.conf
```sh
[options]
HoldPkg     = pacman glibc
Architecture = auto
SigLevel    = Required DatabaseOptional
LocalFileSigLevel = Optional

[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist

[multilib]
Include = /etc/pacman.d/mirrorlist
```

### PR DESCRIPTION
**Pull request by pfeifferj**
Fixes crash when running paru -Qui on systems with inconsistent package database state.

The crash occurred because db.pkg(target) would return PkgNotFound error for packages that were removed or in an inconsistent state, and the unwrap would panic instead of handling the error.

Fixes #1340

### CODE REVIEW

File: src/query.rs [hunk 1]
```diff
@@ -67,17 +67,18 @@ pub async fn print_upgrade_list(config: &mut Config) -> Result<i32> {
                 if !config.mode.pkgbuild() {
                     return true;
                 }
-                let local_pkg = db.pkg(target).unwrap();
```
Comment (Morganamilo) [inline src/query.rs]: This shouldn't need to change much. Just remove `local_pkg =`...
